# Generated by Django 2.1.7 on 2019-04-07 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_mixture_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('URL', models.URLField(blank=True, db_index=True, max_length=128)),
            ],
        ),
    ]
