# Generated by Django 2.1.7 on 2019-03-26 04:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250, unique_for_date='Deadline')),
                ('Link', models.URLField(blank=True, db_index=True, max_length=128, unique=True)),
                ('Description', models.TextField()),
                ('Deadline', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('-Deadline',),
            },
        ),
    ]
