# Generated by Django 2.1.7 on 2019-04-09 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobs',
            old_name='Job_Id',
            new_name='blog_Id',
        ),
    ]
