# Generated by Django 2.1.7 on 2019-04-06 07:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20190406_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='Deadline',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
