# Generated by Django 2.1.7 on 2019-04-09 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_remove_jobs_job_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='Job_Id',
            field=models.IntegerField(default=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='flag',
            field=models.BooleanField(default=1),
        ),
    ]
