# Generated by Django 2.1.7 on 2019-04-07 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_remove_jobs_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='flag',
            field=models.IntegerField(default=0),
        ),
    ]
