# Generated by Django 2.1.7 on 2019-04-09 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_auto_20190409_0607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='Job_Id',
            field=models.IntegerField(default=True),
        ),
    ]
