# Generated by Django 2.1.7 on 2019-04-09 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_auto_20190409_0609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='flag',
            field=models.BooleanField(default=0),
        ),
    ]
