# Generated by Django 2.0.1 on 2018-06-19 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_mixture_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mixture',
            name='author',
        ),
    ]
