# Generated by Django 2.0.1 on 2018-07-10 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20180710_2204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='number',
        ),
    ]
