# Generated by Django 2.0.1 on 2018-07-10 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20180710_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
