# Generated by Django 2.0.5 on 2018-07-13 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20180713_0332'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, upload_to='products/profile/%Y%m/%d'),
        ),
    ]
