# Generated by Django 2.0.5 on 2018-07-21 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_userprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='description',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/profile/%Y%/%m/%d'),
        ),
    ]
