# Generated by Django 2.0.5 on 2018-07-24 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_auto_20180722_0524'),
    ]

    operations = [
        migrations.AddField(
            model_name='mixture',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='products/profile/'),
        ),
    ]
