# Generated by Django 2.0.5 on 2018-07-24 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_mixture_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mixture',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='products/mixture/'),
        ),
    ]
